/**
 * Source canonique du wording FR — Ubuntu IA MVP.
 * Ne pas dupliquer ces chaînes dans les composants.
 */
export const copy = {
  product: {
    name: "Ubuntu IA",
    org: "SOFICAU UBUNTU GROUP",
    markAlt: "Marque provisoire SOFICAU Ubuntu Group — à remplacer par le fichier logo officiel",
  },
  meta: {
    title: "Ubuntu IA",
    description:
      "Agent d'entreprise SOFICAU UBUNTU GROUP. Posez une question sur les documents internes et obtenez une réponse sourcée.",
  },
  nav: {
    conversation: "Conversation",
    documents: "Documents",
    signOut: "Se déconnecter",
    roleAdmin: "Administrateur",
    roleUser: "Collaborateur",
    unnamed: "Compte sans nom",
    menuOpen: "Ouvrir le menu",
    menuClose: "Fermer le menu",
    menuTitle: "Menu Ubuntu IA",
    tipConversation: "Ouvrir l'espace de conversation.",
    tipDocuments: "Ouvrir la base documentaire.",
    tipSignOut: "Fermer votre session Ubuntu IA.",
    tipMenuOpen: "Ouvrir le menu de navigation.",
    tipMenuClose: "Fermer le menu de navigation.",
    tipHome: "Retourner à l'accueil Ubuntu IA.",
  },
  tips: {
    cancel: "Annuler et ne rien modifier.",
    confirm: "Valider cette action.",
    close: "Fermer cette fenêtre.",
    retry: "Relancer cette opération.",
    selectOpen: "Ouvrir la liste pour choisir une option.",
    tabDocuments: "Gérer les fichiers et pages indexés.",
    tabAccess: "Gérer les invitations et les comptes.",
    tabDomains: "Gérer les domaines e-mail autorisés.",
    tabFeedback: "Relire les retours utilisateurs pour ajuster Ubuntu IA.",
    backToChat: "Retourner à la conversation.",
  },
  auth: {
    title: "Connexion à Ubuntu IA",
    lead: "Accès réservé aux collaborateurs de SOFICAU UBUNTU GROUP et de ses entités.",
    emailLabel: "Adresse e-mail professionnelle",
    emailHint: "Utilisez l'adresse fournie par votre entité.",
    emailPlaceholder: "prenom.nom@ubuntu-grp.com",
    passwordLabel: "Mot de passe",
    forgotLink: "Mot de passe oublié ?",
    tipForgot: "Recevoir un lien pour choisir un nouveau mot de passe.",
    submit: "Se connecter",
    submitting: "Connexion en cours",
    tipSubmit: "Ouvrir Ubuntu IA avec votre compte.",
    demoNotice:
      "La connexion vérifie un compte réel. Si vous avez reçu une invitation, ouvrez le lien du message pour choisir votre mot de passe.",
    errors: {
      emailRequired: "Indiquez votre adresse e-mail professionnelle.",
      emailFormat: "Cette adresse n'est pas reconnue comme un e-mail valide.",
      emailDomain:
        "Seules les adresses {domains} sont acceptées pour le moment.",
      emailDomainEmpty:
        "Aucun domaine e-mail n'est autorisé pour le moment. Contactez un administrateur.",
      passwordRequired: "Indiquez votre mot de passe.",
      passwordLength: "Le mot de passe doit contenir au moins 8 caractères.",
      credentials:
        "L'adresse ou le mot de passe ne correspond pas. Vérifiez votre saisie.",
      locked:
        "Connexion temporairement bloquée après plusieurs tentatives. Réessayez dans quelques minutes ou contactez un administrateur.",
      suspended:
        "Ce compte est suspendu. Vous ne pouvez pas vous connecter tant qu'un administrateur ne l'a pas réactivé.",
      unavailable:
        "Le service de connexion n'est pas joignable pour le moment. Réessayez plus tard ou contactez un administrateur.",
    },
  },
  chat: {
    pageTitle: "Conversation",
    newConversation: "Nouvelle conversation",
    newConversationShort: "Nouveau",
    untitled: "Nouvelle conversation",
    sidebarLabel: "Historique des conversations",
    composerLabel: "Votre question",
    composerPlaceholder:
      "Posez une question ou confiez une tâche — analyse, code, document, image, plan d'action…",
    composerHint: "Entrée pour envoyer · Maj + Entrée pour un saut de ligne",
    composerDrop: "Déposez les fichiers ici pour les joindre à la demande.",
    send: "Envoyer",
    sending: "Traitement en cours",
    stop: "Arrêter",
    stoppedTitle: "Traitement interrompu",
    stoppedBody:
      "La génération a été arrêtée. Votre message est conservé. Vous pouvez relancer.",
    attachMenu: "Ajouter des fichiers ou des outils",
    attachMenuTitle: "Ajouter à la demande",
    attachFile: "Joindre un fichier",
    attachPhoto: "Joindre des photos",
    attachCamera: "Prendre une photo",
    toolDocuments: "Recherche documentaire",
    toolDocumentsHint:
      "Si la demande concerne un document indexé, Ubuntu IA s'appuie d'abord sur la base interne. Sinon, ces documents ne sont ni utilisés ni cités.",
    toolWeb: "Recherche web",
    toolWebHint:
      "Si la demande n'a pas trait aux documents indexés, Ubuntu IA répond avec le modèle et le web, sans afficher de sources internes.",
    toolImage: "Créer une image",
    toolImageOn:
      "Création d'image activée pour la prochaine réponse. La recherche interne et le web restent pris en compte.",
    toolImageOff: "Création d'image désactivée.",
    toolImageArmed: "Image : activée pour l'envoi suivant",
    toolImageDisarm: "Désactiver la création d'image",
    generatedImageAlt: "Image générée par Ubuntu IA",
    imageFailed: "L'image n'a pas pu être générée. Réessayez dans un instant.",
    toolResearch: "Analyse approfondie",
    toolResearchHint:
      "Toujours active. Ubuntu IA agit comme un agent : il classe chaque message (question ou tâche), choisit les outils, puis exécute. Les documents et la mise en forme passent par Claude Opus 5 et les skills Anthropic.",
    toolCanvas: "Canevas",
    toolCanvasOn:
      "Canevas activé pour l'envoi suivant. Ubuntu IA produira un livrable fini (document, plan, code ou tableau).",
    toolCanvasOff: "Canevas désactivé.",
    toolCanvasArmed: "Canevas : activé pour l'envoi suivant",
    toolCanvasDisarm: "Désactiver le canevas",
    canvasHeading: "Livrable",
    toolFile: "Fichier téléchargeable",
    toolFileOn:
      "Un fichier téléchargeable sera produit pour l'envoi suivant (PDF, Word, Excel, PowerPoint ou le format demandé), avec Claude Opus et les skills Claude Office.",
    toolFileOff: "Génération de fichier désactivée.",
    toolFileArmed: "Fichier : activé pour l'envoi suivant",
    toolFileDisarm: "Désactiver la génération de fichier",
    tipToolFile: "Produire un fichier téléchargeable (PDF, Word, Excel, PowerPoint…).",
    tipDisarmFile: "Désactiver la génération de fichier pour l'envoi suivant.",
    filesHeading: "Fichiers à télécharger",
    downloadFile: "Télécharger",
    downloadImage: "Télécharger l'image",
    tipDownloadFile: "Enregistrer ce fichier sur votre appareil.",
    tipDownloadImage: "Enregistrer cette image sur votre appareil.",
    fileKind: {
      pdf: "PDF",
      docx: "Word",
      xlsx: "Excel",
      pptx: "PowerPoint",
      csv: "CSV",
      txt: "Texte",
      md: "Markdown",
      json: "JSON",
      png: "Image",
      jpeg: "Image",
      webp: "Image",
    },
    tipAttachMenu: "Joindre un fichier ou activer un outil.",
    tipDictate: "Dicter votre question. Le texte s'ajoute dans le champ.",
    tipDictateStop: "Arrêter la dictée.",
    tipSend: "Envoyer la question.",
    tipStop: "Arrêter la génération en cours.",
    tipVoiceMode: "Parler directement avec Ubuntu IA, comme au téléphone.",
    tipRemoveAttachment: "Retirer « {name} » de l'envoi.",
    tipDisarmImage: "Désactiver la création d'image pour l'envoi suivant.",
    tipDisarmCanvas: "Désactiver le canevas pour l'envoi suivant.",
    tipAttachFile: "Joindre un PDF, Word, Excel ou un autre fichier.",
    tipAttachPhoto: "Joindre une ou plusieurs photos.",
    tipAttachCamera: "Prendre une photo avec l'appareil.",
    tipToolDocuments: "Toujours active : cherche d'abord dans les documents indexés.",
    tipToolWeb: "Toujours active : complète avec le web si le sujet n'est pas interne.",
    tipToolImage: "Activer ou désactiver la création d'une image.",
    tipToolResearch: "Toujours active : analyse approfondie de la question et des pièces.",
    tipToolCanvas: "Activer ou désactiver un livrable fini (document, plan, code).",
    tipToolDictate: "Dicter directement depuis ce menu.",
    tipVoiceClose: "Fermer le mode vocal.",
    tipVoiceSend: "Envoyer la question dictée.",
    tipVoiceRetry: "Relancer la conversation vocale.",
    toolUnavailableTitle: "Outil non disponible",
    toolUnavailableBody: "Cet outil n'est pas disponible pour le moment.",
    toolUnavailableClose: "Compris",
    dictate: "Dictée vocale",
    dictateStop: "Arrêter la dictée",
    dictateListening: "Dictée en cours. Parlez, le texte s'ajoute à votre question.",
    voiceMode: "Mode vocal",
    voiceModeClose: "Raccrocher",
    voiceListening: "Je vous écoute",
    voiceListeningHint:
      "Parlez naturellement. Ubuntu IA vous entend en continu : vous pouvez la couper, rebondir, ou enchaîner comme au téléphone.",
    voiceConnecting: "Mise en ligne…",
    voiceConnectingHint: "Ouverture du canal vocal temps réel.",
    voiceThinking: "Je vérifie…",
    voiceProcessing: "Je prépare la réponse…",
    voiceSpeaking: "Ubuntu IA vous répond",
    voiceMissed: "Je n'ai pas pu répondre. Reprenez, je vous écoute.",
    voiceSend: "Envoyer",
    voiceRetry: "Relancer",
    voiceUnsupportedTitle: "La voix n'est pas disponible",
    voiceUnsupportedBody:
      "Ce navigateur ne permet pas une conversation vocale temps réel. Ouvrez Ubuntu IA dans Chrome, Edge ou Safari récent.",
    voiceDeniedTitle: "Micro non autorisé",
    voiceDeniedBody:
      "Autorisez le microphone dans les paramètres du navigateur, puis relancez le mode vocal.",
    voiceErrorTitle: "La conversation vocale s'est interrompue",
    voiceErrorBody: "Réessayez, ou posez votre question par écrit.",
    attachmentOnlyPrompt:
      "Analyse les pièces jointes avec toutes tes capacités. Si elles concernent le travail interne, croise-les avec les documents indexés ; sinon, appuie-toi sur leur contenu, tes connaissances et le web.",
    attachmentsLabel: "Pièces jointes",
    removeAttachment: "Retirer {name}",
    attachmentTooBig: "« {name} » dépasse 20 Mo. Réduisez-le avant de le joindre.",
    attachmentType:
      "« {name} » n'est pas accepté. Joignez un PDF, Word, Excel, PowerPoint, CSV, texte, image ou infographie.",
    attachmentLimit: "Vous pouvez joindre jusqu'à 8 fichiers à une question.",
    historyOpen: "Conversations",
    historyClose: "Fermer l'historique",
    menuOpen: "Ouvrir le menu",
    menuClose: "Fermer le menu",
    copyAnswer: "Copier la réponse",
    copyAnswerDone: "Réponse copiée",
    copyAnswerError: "La réponse n'a pas pu être copiée",
    copyQuestion: "Copier la question",
    copyQuestionDone: "Question copiée",
    copyQuestionError: "La question n'a pas pu être copiée",
    tipCopyQuestion: "Copier le texte de la question.",
    editQuestion: "Modifier la question",
    tipEditQuestion: "Modifier cette question et la renvoyer à Ubuntu IA.",
    editQuestionLabel: "Votre question",
    editQuestionHint: "Ctrl+Entrée pour renvoyer. Échap pour annuler.",
    editQuestionOffline: "Reconnectez-vous pour renvoyer la question.",
    resendQuestion: "Renvoyer",
    cancelEdit: "Annuler",
    tipResendQuestion: "Envoyer la question modifiée à Ubuntu IA.",
    tipCancelEdit: "Annuler la modification et garder le texte d'origine.",
    sourcesHeading: "Sources utilisées",
    extractLabel: "Extrait",
    sourceShow: "Voir le détail",
    sourceHide: "Réduire",
    sourceToggle: "Source {n}, {title}",
    sourceIndex: "Document indexé",
    sourceWeb: "Recherche web",
    sourceOpen: "Ouvrir la source",
    sourceOpenLabel: "Ouvrir la source {title} dans un nouvel onglet",
    tipSourceOpen: "Ouvrir cette source dans un nouvel onglet.",
    emptyTitle: "Posez votre question",
    emptyBody:
      "Ubuntu IA s'appuie sur openai/gpt-6-astra : analyse, code, documents, calcul, images, recherche web et lecture de fichiers. Les documents internes priment lorsqu'ils concernent le sujet.",
    emptyHint: "Exemple : Rédige un plan d'action, analyse ce fichier, ou explique une procédure interne.",
    historyLoading: "Chargement de vos conversations",
    historyErrorTitle: "L'historique n'a pas pu être chargé",
    historyErrorBody: "Vos conversations enregistrées sont inaccessibles pour le moment.",
    retryHistory: "Réessayer le chargement",
    tipHistoryOpen: "Afficher la liste des conversations.",
    tipNewConversation: "Commencer une nouvelle conversation.",
    tipOpenConversation: "Ouvrir cette conversation.",
    tipRenameConversation: "Renommer cette conversation.",
    tipDeleteConversation: "Supprimer cette conversation.",
    renameConversation: "Renommer",
    renameConversationTitle: "Renommer la conversation",
    renameConversationLabel: "Nouveau titre",
    renameConversationHint: "80 caractères maximum.",
    renameConversationConfirm: "Enregistrer",
    renameConversationPending: "Enregistrement…",
    renameConversationError: "La conversation n'a pas pu être renommée.",
    renameConversationEmpty: "Indiquez un titre pour cette conversation.",
    deleteConversation: "Supprimer",
    deleteConversationTitle: "Supprimer cette conversation ?",
    deleteConversationBody:
      "« {title} » sera retirée de votre historique. Les messages disparaîtront. Cette action est irréversible.",
    deleteConversationConfirm: "Supprimer",
    deleteConversationPending: "Suppression…",
    deleteConversationError: "La conversation n'a pas pu être supprimée.",
    tipRetryHistory: "Recharger l'historique des conversations.",
    tipReformulate: "Revenir au champ pour reformuler la demande.",
    tipRetryAnswer: "Relancer le traitement pour ce message.",
    tipCopyAnswer: "Copier le texte de la réponse.",
    noConversations: "Aucune conversation pour l'instant.",
    validationEmpty: "Saisissez une demande, ou joignez un fichier.",
    pendingAnnouncement: "Préparation de la réponse…",
    stepsToggle: "Étapes du traitement",
    stepsPlan: "Analyse de la demande…",
    stepsPlanDone: "Intention identifiée.",
    stepsAttachments: "Lecture des pièces jointes…",
    stepsAttachmentsDone: "Pièces jointes lues.",
    stepsSearch: "Recherche dans les documents internes…",
    stepsSearchDone: "Passages internes trouvés.",
    stepsSearchEmpty: "Aucun document interne pertinent.",
    stepsSearchSkip: "Recherche interne non nécessaire pour cette demande.",
    stepsSearchError: "La recherche documentaire n'a pas abouti.",
    stepsTools: "Sélection et exécution des outils…",
    stepsToolsDone: "Outils prêts.",
    stepsWeb: "Recherche sur le web…",
    stepsWebFetch: "Lecture des pages web…",
    stepsWebDone: "Pages web consultées.",
    stepsWebEmpty: "Aucune page web supplémentaire.",
    stepsAnalyze: "Analyse des passages pertinents…",
    stepsAnalyzeDone: "Passages prêts pour la rédaction.",
    stepsWrite: "Rédaction de la réponse…",
    stepsWriteDone: "Réponse rédigée.",
    stepsImage: "Création de l'image…",
    stepsImageDone: "Image générée.",
    stepsImageError: "L'image n'a pas pu être générée.",
    stepsFile: "Préparation du livrable…",
    stepsFileContent: "Préparation du contenu du document…",
    stepsFileBuild: "Création du fichier {format}…",
    stepsFileDone: "Livrable prêt.",
    stepsFileError: "Le fichier n'a pas pu être généré.",
    streamCaret: "Réponse en cours d'écriture",
    noSourceTitle: "Aucune source ne permet de répondre",
    noSourceBody:
      "Ubuntu IA n'a trouvé ni document indexé pertinent, ni résultat web exploitable, ni contenu lisible dans les pièces jointes. Reformulez la demande, joignez un fichier, ou demandez à un administrateur d'ajouter une source.",
    noSourceAction: "Reformuler la demande",
    errorTitle: "La réponse n'a pas pu être générée",
    errorBody:
      "Votre question est conservée. Vous pouvez relancer la recherche sans la ressaisir.",
    retryAnswer: "Relancer la recherche",
    timeoutTitle: "Le délai d'attente est dépassé",
    timeoutBody:
      "Ubuntu IA n'a pas confirmé si une réponse a été produite. Vérifiez l'historique avant de renvoyer la même question, pour éviter un doublon.",
    offlineTitle: "Connexion interrompue",
    offlineBody:
      "La recherche ne peut pas aboutir tant que le réseau est indisponible. Votre question reste affichée.",
    offlineBanner: "Vous êtes hors ligne. Les nouvelles questions ne peuvent pas être envoyées.",
    feedbackUp: "Réponse utile",
    feedbackDown: "Réponse à améliorer",
    tipFeedbackUp: "Indiquer que cette réponse convient.",
    tipFeedbackDown: "Indiquer que cette réponse ne convient pas.",
    tipFeedbackComment: "Envoyer une précision sur ce qui n'allait pas.",
    feedbackCommentLabel: "Que faudrait-il améliorer ?",
    feedbackCommentHint: "Facultatif. Ton, exactitude, information manquante…",
    feedbackCommentSubmit: "Envoyer le commentaire",
    feedbackSaved: "Votre avis a été enregistré.",
    memoryOpen: "Mémoire",
    tipMemoryOpen: "Voir ce qu'Ubuntu IA retient de vous.",
    memoryTitle: "Ce qu'Ubuntu IA retient",
    memoryLead:
      "Préférences et faits que vous avez exprimés. Ils s'appliquent aux prochaines conversations. Vous pouvez en effacer un à tout moment.",
    memoryLoading: "Chargement de la mémoire",
    memoryRetry: "Réessayer",
    tipMemoryRetry: "Recharger la mémoire enregistrée.",
    memoryEmptyTitle: "Aucun souvenir pour l'instant",
    memoryEmptyBody:
      "Si vous indiquez une préférence (« je préfère des réponses courtes »), Ubuntu IA la retiendra pour les conversations suivantes.",
    memoryDelete: "Oublier",
    tipMemoryDelete: "Effacer ce souvenir.",
    memoryDeleteTitle: "Oublier ce souvenir ?",
    memoryDeleteBody:
      "Ubuntu IA ne s'appuiera plus sur cette information. Vous pourrez la redire plus tard si besoin.",
    memoryDeleteConfirm: "Oublier",
    memoryKeys: {
      preference_longueur: "Longueur des réponses",
      preference_ton: "Ton",
      preference_format_rapport: "Format des livrables",
      resume: "Synthèse",
    },
  },
  admin: {
    tabs: {
      label: "Sections d'administration",
      documents: "Documents",
      access: "Accès",
      domains: "Domaines e-mail",
      feedback: "Retours",
    },
    pageTitle: "Documents indexés",
    pageLead:
      "Ajoutez, suivez ou retirez les fichiers et pages qui alimentent Ubuntu IA. Une page web est indexée une par une.",
    uploadTitle: "Indexer un fichier",
    uploadLead:
      "PDF, Word, Excel (.xlsx, .xls), PowerPoint, CSV, images et infographies, jusqu'à 20 Mo. Le modèle lit le texte, les tableaux et le contenu visuel.",
    uploadDrop: "Déposez un fichier ici, ou",
    uploadBrowse: "choisir un fichier",
    urlTitle: "Indexer une page web",
    urlLabel: "Adresse de la page",
    urlPlaceholder: "https://soficau-ubuntu.com/page",
    urlHint: "Une seule page à la fois. L'indexation d'un site entier n'est pas disponible.",
    urlSubmit: "Indexer la page",
    urlSubmitting: "Récupération de la page",
    categoryLabel: "Catégorie",
    categoryIndexLabel: "Catégorie d'indexation",
    categoryIndexHint:
      "Les nouveaux fichiers et pages seront classés dans cette catégorie.",
    categoryFilterLabel: "Afficher",
    categoryFilterHint:
      "Ne voir que les fichiers et liens d'une catégorie, ou toute la base.",
    categoryFilterAll: "Toutes les catégories",
    categoriesTitle: "Catégories",
    categoryAddTitle: "Nouvelle catégorie",
    categoryAddLabel: "Nom de la catégorie",
    categoryAddPlaceholder: "Ex. Juridique",
    categoryAddHint: "Elle sera proposée à l'indexation et dans le filtre.",
    categoryAdd: "Ajouter la catégorie",
    categoryAdded: "La catégorie « {label} » est disponible.",
    emptyFilterTitle: "Aucun document dans « {label} »",
    emptyFilterBody:
      "Aucun fichier ni lien n'est classé dans cette catégorie pour le moment. Indexez une source ici, ou affichez toutes les catégories.",
    emptyFilterAction: "Voir toutes les catégories",
    tableLabel: "Documents de la base de connaissances",
    columns: {
      title: "Titre",
      category: "Catégorie",
      source: "Origine",
      status: "Indexation",
      date: "Ajouté le",
      actions: "Actions",
    },
    sourceFile: "Fichier",
    sourceUrl: "Page web",
    status: {
      en_attente: "En attente",
      en_cours: "Indexation en cours",
      termine: "Indexé",
      erreur: "Échec",
    },
    retryIndex: "Relancer l'indexation",
    delete: "Supprimer",
    loading: "Chargement des documents",
    loadErrorTitle: "La liste des documents n'a pas pu être chargée",
    loadErrorBody: "Les documents déjà indexés n'apparaissent pas. La base n'a pas été modifiée.",
    retryLoad: "Réessayer",
    emptyFirstTitle: "Aucun document n'est encore indexé",
    emptyFirstBody:
      "Ajoutez un PDF, Word, Excel, PowerPoint, CSV, image ou infographie, ou l'adresse d'une page web, pour constituer la base de connaissances.",
    emptyClearedTitle: "Tous les documents ont été retirés",
    emptyClearedBody:
      "La base de recherche est vide. Les réponses déjà affichées dans les conversations restent visibles, mais les nouvelles questions n'auront plus de source.",
    emptyAction: "Ajouter un fichier",
    queued: "« {title} » est en cours d'indexation.",
    indexed: "« {title} » est indexé et disponible pour la recherche.",
    indexFailed: "L'indexation de « {title} » a échoué. Le document n'est pas cherchable.",
    deleted: "« {title} » a été retiré de la base de recherche.",
    errors: {
      fileType:
        "Ce format n'est pas accepté. Envoyez un PDF, Word, Excel, PowerPoint, CSV, texte, image ou infographie.",
      fileSize: "Le fichier dépasse 20 Mo. Réduisez-le ou découpez-le avant de l'envoyer.",
      ingest: "L'indexation n'a pas pu démarrer. Réessayez dans un instant.",
      urlRequired: "Indiquez l'adresse complète de la page à indexer.",
      urlFormat:
        "Cette adresse n'est pas valide. Utilisez une URL complète, par exemple https://soficau-ubuntu.com/page.",
      category: {
        required: "Indiquez le nom de la catégorie.",
        invalid: "Ce nom n'est pas utilisable. Saisissez des lettres ou des chiffres.",
        duplicate: "Cette catégorie existe déjà.",
        unavailable: "La catégorie n'a pas pu être enregistrée. Réessayez.",
      },
    },
    confirm: {
      cancel: "Annuler",
    },
    indexFileTitle: "Indexer ce fichier ?",
    indexFileBody:
      "« {title} » sera classé dans {category}. L'indexation ne commence qu'après confirmation.",
    indexFileConfirm: "Indexer le fichier",
    indexUrlTitle: "Indexer cette page ?",
    indexUrlBody:
      "{url} sera classée dans {category}. L'indexation ne commence qu'après confirmation.",
    indexUrlConfirm: "Indexer la page",
    addCategoryConfirmTitle: "Ajouter cette catégorie ?",
    addCategoryConfirmBody:
      "« {label} » sera proposée à l'indexation et dans le filtre des documents.",
    addCategoryConfirm: "Ajouter la catégorie",
    categorySaving: "Enregistrement de la catégorie",
    retryTitle: "Relancer l'indexation ?",
    retryBody: "L'indexation de « {title} » va redémarrer. Le document n'est pas encore cherchable.",
    retryConfirm: "Relancer l'indexation",
    retryAll: "Relire les fichiers déjà indexés",
    tipRetryAll: "Relire tous les documents déjà indexés.",
    tipRetryLoad: "Recharger la liste des documents.",
    tipAddFile: "Choisir un fichier à indexer.",
    tipShowAllCategories: "Afficher tous les documents, toutes catégories confondues.",
    tipRetryIndex: "Relancer l'indexation de ce document.",
    tipDeleteDocument: "Retirer ce document de la base de recherche.",
    tipAddCategory: "Enregistrer cette catégorie dans le filtre et l'indexation.",
    tipIndexUrl: "Indexer le contenu de cette page web.",
    tipBrowseFile: "Ouvrir l'explorateur pour choisir un fichier.",
    retryAllTitle: "Relire tous les documents ?",
    retryAllBody:
      "Ubuntu IA va relire les fichiers et pages déjà enregistrés, y compris les images, tableurs et présentations, avec les extracteurs actuels.",
    retryAllConfirm: "Relire tous les documents",
    retryAllQueued: "{count} document(s) sont en cours de relecture.",
    deleteTitle: "Supprimer « {title} » ?",
    deleteBody:
      "Ce document et tous ses extraits seront retirés de la recherche. Les réponses déjà affichées dans les conversations ne changeront pas, mais Ubuntu IA ne s'appuiera plus sur cette source.",
    deleteConfirm: "Supprimer le document",
    deleteCancel: "Conserver le document",
    deleting: "Suppression en cours",
    forbiddenTitle: "Cette page est réservée aux administrateurs",
    forbiddenBody:
      "Vous êtes connecté en tant que collaborateur. L'ajout et la suppression de documents ne sont pas disponibles sur ce compte.",
    forbiddenAction: "Retourner à la conversation",
    domains: {
      pageTitle: "Domaines e-mail autorisés",
      pageLead:
        "Seules les adresses de ces domaines peuvent se connecter à Ubuntu IA. Retirer un domaine bloque immédiatement les prochaines connexions liées.",
      addTitle: "Autoriser un domaine",
      fieldLabel: "Domaine",
      fieldHint: "Sans @. Exemple : ubuntu-grp.com",
      fieldPlaceholder: "ubuntu-grp.com",
      add: "Ajouter le domaine",
      adding: "Ajout en cours",
      tipAdd: "Autoriser les connexions depuis ce domaine.",
      tipDelete: "Interdire les prochaines connexions depuis ce domaine.",
      tipRetryLoad: "Recharger la liste des domaines.",
      addConfirmTitle: "Autoriser ce domaine ?",
      addConfirmBody: "Les adresses @{domain} pourront ensuite se connecter à Ubuntu IA.",
      addConfirm: "Ajouter le domaine",
      loading: "Chargement des domaines autorisés",
      loadErrorTitle: "La liste des domaines n'a pas pu être chargée",
      loadErrorBody:
        "Les domaines déjà enregistrés n'apparaissent pas. La liste utilisée à la connexion n'a pas été modifiée.",
      retryLoad: "Réessayer",
      emptyTitle: "Aucun domaine n'est encore autorisé",
      emptyBody:
        "Ajoutez au moins un domaine professionnel, sinon personne ne pourra se connecter.",
      tableLabel: "Domaines autorisés à la connexion",
      columns: {
        domain: "Domaine",
        date: "Ajouté le",
        actions: "Actions",
      },
      delete: "Retirer",
      lastHint:
        "Au moins un domaine doit rester autorisé, sinon plus personne ne pourra se connecter.",
      added: "Les adresses @{domain} peuvent maintenant se connecter.",
      removed: "Les adresses @{domain} ne sont plus acceptées à la connexion.",
      deleteTitle: "Retirer @{domain} ?",
      deleteBody:
        "Les prochaines connexions avec une adresse @{domain} seront refusées. Les sessions déjà ouvertes restent actives jusqu'à la déconnexion.",
      deleteBodyOwn:
        "Votre propre adresse utilise @{domain}. Après ce retrait, vous ne pourrez plus vous reconnecter avec ce compte tant que le domaine n'est pas réautorisé.",
      deleteConfirm: "Retirer le domaine",
      deleteCancel: "Conserver le domaine",
      deleting: "Retrait en cours",
      errors: {
        required: "Indiquez le domaine à autoriser.",
        invalid:
          "Ce domaine n'est pas reconnu. Saisissez un nom d'hôte, par exemple ubuntu-grp.com.",
        duplicate: "Ce domaine est déjà autorisé.",
        last: "Il doit rester au moins un domaine autorisé.",
        unavailable:
          "Le domaine n'a pas pu être enregistré. Réessayez, la liste n'a pas changé.",
      },
    },
    feedback: {
      pageTitle: "Retours des conversations",
      pageLead:
        "Les avis négatifs récents, avec la question et la réponse concernées, pour ajuster les consignes d'Ubuntu IA.",
      filterLabel: "Afficher",
      filterNegative: "Retours négatifs",
      filterPositive: "Retours positifs",
      filterAll: "Tous les retours",
      loading: "Chargement des retours",
      loadErrorTitle: "Les retours n'ont pas pu être chargés",
      loadErrorBody: "La revue n'est pas disponible pour le moment. Réessayez.",
      retryLoad: "Réessayer",
      tipRetryLoad: "Recharger les retours.",
      emptyTitle: "Aucun retour pour le moment",
      emptyBody:
        "Lorsqu'un collaborateur met un pouce bas, l'avis apparaît ici avec le contexte de la conversation.",
      questionLabel: "Question",
      answerLabel: "Réponse",
      commentLabel: "Commentaire",
      typeNegative: "À améliorer",
      typePositive: "Utile",
      anonymous: "Compte sans nom",
    },
    access: {
      pageTitle: "Accès",
      pageLead:
        "Invitez une personne, puis gérez son nom, son rôle et son accès. Un compte suspendu ne peut plus se connecter tant qu'il n'est pas réactivé.",
      inviteTitle: "Inviter une personne",
      prenomLabel: "Prénom",
      nomLabel: "Nom",
      emailLabel: "Adresse e-mail",
      emailHint: "L'invitation part vers cette adresse. Le domaine doit être autorisé.",
      roleLabel: "Rôle",
      roleAdmin: "Administrateur",
      roleUser: "Collaborateur",
      send: "Envoyer l'invitation",
      sending: "Envoi de l'invitation",
      tipSend: "Envoyer un e-mail d'invitation pour créer un compte.",
      tipResend: "Renvoyer le lien de création de mot de passe.",
      tipRetryLoad: "Recharger la liste des accès.",
      tipEdit: "Modifier le nom et le rôle de ce compte.",
      tipSuspend: "Empêcher cette personne de se connecter.",
      tipReactivate: "Autoriser de nouveau la connexion avec ses identifiants.",
      tipDelete: "Supprimer définitivement ce compte.",
      tipSelfLocked: "Vous ne pouvez pas suspendre ni supprimer votre propre compte.",
      tipLastAdmin: "Il doit rester au moins un administrateur actif.",
      sent: "Invitation envoyée à {email}. La personne doit d'abord configurer son mot de passe.",
      inviteConfirmTitle: "Envoyer cette invitation ?",
      inviteConfirmBody:
        "{name} ({email}) recevra un lien pour choisir son mot de passe en tant que {role}.",
      inviteConfirm: "Envoyer l'invitation",
      resendConfirmTitle: "Renvoyer le lien ?",
      resendConfirmBody: "Un nouveau lien d'invitation sera envoyé à {email}.",
      resendConfirm: "Renvoyer le lien",
      loading: "Chargement des accès",
      loadErrorTitle: "Les accès n'ont pas pu être chargés",
      loadErrorBody: "La liste des comptes et des invitations n'apparaît pas. Rien n'a été modifié.",
      retryLoad: "Réessayer",
      peopleTitle: "Comptes",
      peopleEmptyTitle: "Aucun compte n'est encore listé",
      peopleEmptyBody: "Les personnes qui auront accepté une invitation apparaîtront ici.",
      peopleLabel: "Comptes Ubuntu IA",
      invitationsTitle: "Invitations",
      invitationsEmptyTitle: "Aucune invitation en cours",
      invitationsEmptyBody: "Envoyez une invitation pour qu'une personne configure son mot de passe.",
      invitationsLabel: "Invitations envoyées",
      resend: "Renvoyer le lien",
      resending: "Nouvel envoi",
      resent: "Un nouveau lien a été envoyé à {email}.",
      columns: {
        name: "Nom",
        email: "E-mail",
        role: "Rôle",
        status: "État",
        date: "Envoyée le",
        actions: "Actions",
      },
      accountStatus: {
        actif: "Actif",
        suspendu: "Suspendu",
      },
      edit: "Modifier",
      editTitle: "Modifier le compte",
      editSave: "Enregistrer les modifications",
      editSaving: "Enregistrement",
      editSaved: "Le compte de {name} a été mis à jour.",
      suspend: "Suspendre",
      suspending: "Suspension",
      suspendTitle: "Suspendre ce compte ?",
      suspendBody:
        "{name} ne pourra plus se connecter avec ses identifiants tant qu'un administrateur ne réactivera pas le compte.",
      suspendConfirm: "Suspendre le compte",
      suspendedToast: "Le compte de {name} est suspendu.",
      reactivate: "Réactiver",
      reactivating: "Réactivation",
      reactivateTitle: "Réactiver ce compte ?",
      reactivateBody:
        "{name} pourra de nouveau se connecter avec ses identifiants actuels.",
      reactivateConfirm: "Réactiver le compte",
      reactivatedToast: "Le compte de {name} est de nouveau actif.",
      delete: "Supprimer",
      deleting: "Suppression",
      deleteTitle: "Supprimer ce compte ?",
      deleteBody:
        "Le compte de {name} sera définitivement retiré. Cette personne ne pourra plus se connecter et ses conversations seront aussi supprimées. Cette action est irréversible.",
      deleteConfirm: "Supprimer définitivement",
      deletedToast: "Le compte de {name} a été supprimé.",
      status: {
        pending: "En attente",
        expired: "Expirée",
        accepted: "Compte créé",
      },
      errors: {
        prenom: "Indiquez le prénom.",
        nom: "Indiquez le nom.",
        email: "Indiquez une adresse e-mail professionnelle valide.",
        role: "Choisissez le rôle Administrateur ou Collaborateur.",
      },
    },
  },
  invite: {
    title: "Configurer votre mot de passe",
    lead: "Bonjour {name}. Choisissez un mot de passe pour ouvrir Ubuntu IA en tant que {role}.",
    passwordLabel: "Mot de passe",
    confirmLabel: "Confirmer le mot de passe",
    passwordHint: "Au moins 8 caractères. Les deux saisies doivent être identiques.",
    submit: "Enregistrer et entrer",
    submitting: "Création du compte",
    tipSubmit: "Enregistrer le mot de passe et entrer dans Ubuntu IA.",
    tipUsedAction: "Aller à l'écran de connexion.",
    tipBackAction: "Retourner à l'écran de connexion.",
    invalidTitle: "Ce lien d'invitation n'est pas valide",
    invalidBody: "Demandez à un administrateur de vous renvoyer une invitation.",
    expiredTitle: "Ce lien d'invitation a expiré",
    expiredBody: "Demandez à un administrateur de vous renvoyer un nouveau lien.",
    usedTitle: "Ce lien a déjà été utilisé",
    usedBody: "Connectez-vous avec l'adresse et le mot de passe déjà choisis.",
    usedAction: "Aller à la connexion",
    backAction: "Retour à la connexion",
    mismatch: "Les deux saisies doivent être identiques.",
    tooShort: "Le mot de passe doit contenir au moins 8 caractères.",
    loading: "Vérification de l'invitation",
  },
  passwordReset: {
    requestTitle: "Mot de passe oublié",
    requestLead:
      "Indiquez l'adresse e-mail de votre compte. Si un compte actif existe, vous recevrez un lien pour choisir un nouveau mot de passe.",
    requestSubmit: "Envoyer le lien",
    requestSubmitting: "Envoi en cours",
    tipRequest: "Recevoir un e-mail de réinitialisation.",
    requestSuccess:
      "Si un compte actif existe pour cette adresse, un e-mail de réinitialisation vient d'être envoyé.",
    requestError: "La demande n'a pas pu être envoyée. Réessayez plus tard.",
    backToLogin: "Retour à la connexion",
    requestAgain: "Demander un nouveau lien",
    tipBackAction: "Retourner à l'écran adapté.",
    confirmTitle: "Nouveau mot de passe",
    confirmLead: "Bonjour {name}. Choisissez un nouveau mot de passe pour Ubuntu IA.",
    passwordLabel: "Nouveau mot de passe",
    confirmLabel: "Confirmer le mot de passe",
    passwordHint: "Au moins 8 caractères. Les deux saisies doivent être identiques.",
    confirmSubmit: "Enregistrer et se connecter",
    confirmSubmitting: "Mise à jour",
    tipConfirm: "Enregistrer le nouveau mot de passe et ouvrir Ubuntu IA.",
    invalidTitle: "Ce lien n'est pas valide",
    invalidBody: "Demandez un nouveau lien depuis l'écran Mot de passe oublié.",
    expiredTitle: "Ce lien a expiré",
    expiredBody: "Les liens de réinitialisation expirent après une heure. Demandez-en un nouveau.",
    usedTitle: "Ce lien a déjà été utilisé",
    usedBody: "Connectez-vous avec le mot de passe déjà choisi, ou demandez un nouveau lien.",
    mismatch: "Les deux saisies doivent être identiques.",
    tooShort: "Le mot de passe doit contenir au moins 8 caractères.",
    loading: "Vérification du lien",
  },
  categories: {
    rh: "RH",
    finance: "Finance",
    procedures: "Procédures",
    projets: "Projets",
    institutionnel: "Institutionnel",
  },
} as const;

export type Copy = typeof copy;
