/**
 * Source canonique du wording FR — Ubuntu IA MVP.
 * Ne pas dupliquer ces chaînes dans les composants.
 */
export const copy = {
  product: {
    name: "Ubuntu IA",
    org: "SOFICAU UBUNTU GROUP",
    markAlt: "Marque provisoire SOFICAU Ubuntu Group — à remplacer par le fichier logo officiel",
  },
  meta: {
    title: "Ubuntu IA",
    description:
      "Agent d'entreprise SOFICAU UBUNTU GROUP. Posez une question sur les documents internes et obtenez une réponse sourcée.",
  },
  nav: {
    conversation: "Conversation",
    documents: "Documents",
    signOut: "Se déconnecter",
    roleAdmin: "Administrateur",
    roleUser: "Collaborateur",
    menuOpen: "Ouvrir le menu",
    menuClose: "Fermer le menu",
    menuTitle: "Menu Ubuntu IA",
  },
  auth: {
    title: "Connexion à Ubuntu IA",
    lead: "Accès réservé aux collaborateurs de SOFICAU UBUNTU GROUP et de ses entités.",
    emailLabel: "Adresse e-mail professionnelle",
    emailHint: "Utilisez l'adresse fournie par votre entité.",
    emailPlaceholder: "prenom.nom@ubuntu-grp.com",
    passwordLabel: "Mot de passe",
    submit: "Se connecter",
    submitting: "Connexion en cours",
    demoNotice:
      "La connexion vérifie un compte réel. Si vous avez reçu une invitation, ouvrez le lien du message pour choisir votre mot de passe.",
    errors: {
      emailRequired: "Indiquez votre adresse e-mail professionnelle.",
      emailFormat: "Cette adresse n'est pas reconnue comme un e-mail valide.",
      emailDomain:
        "Seules les adresses {domains} sont acceptées pour le moment.",
      emailDomainEmpty:
        "Aucun domaine e-mail n'est autorisé pour le moment. Contactez un administrateur.",
      passwordRequired: "Indiquez votre mot de passe.",
      passwordLength: "Le mot de passe doit contenir au moins 8 caractères.",
      credentials:
        "L'adresse ou le mot de passe ne correspond pas. Vérifiez votre saisie.",
      locked:
        "Connexion temporairement bloquée après plusieurs tentatives. Réessayez dans quelques minutes ou contactez un administrateur.",
      unavailable:
        "Le service de connexion n'est pas joignable pour le moment. Réessayez plus tard ou contactez un administrateur.",
    },
  },
  chat: {
    pageTitle: "Conversation",
    newConversation: "Nouvelle conversation",
    newConversationShort: "Nouveau",
    untitled: "Nouvelle conversation",
    sidebarLabel: "Historique des conversations",
    composerLabel: "Votre question",
    composerPlaceholder: "Posez une question sur les documents internes…",
    composerHint: "Entrée pour envoyer · Maj + Entrée pour un saut de ligne",
    composerDrop: "Déposez les fichiers ici pour les joindre à la question.",
    send: "Envoyer",
    sending: "Recherche en cours",
    stop: "Arrêter la recherche",
    stoppedTitle: "Recherche interrompue",
    stoppedBody:
      "La génération a été arrêtée. Votre question est conservée. Vous pouvez relancer la recherche.",
    attachMenu: "Ajouter des fichiers ou des outils",
    attachMenuTitle: "Ajouter à la question",
    attachFile: "Joindre un fichier",
    attachPhoto: "Joindre des photos",
    attachCamera: "Prendre une photo",
    toolDocuments: "Recherche documentaire",
    toolDocumentsHint: "Toujours active. Ubuntu IA s'appuie uniquement sur les documents indexés.",
    toolWeb: "Recherche web",
    toolImage: "Créer une image",
    toolResearch: "Analyse approfondie",
    toolCanvas: "Canevas",
    toolUnavailableTitle: "Outil non disponible",
    toolUnavailableBody:
      "Ubuntu IA est un agent documentaire interne. Cet outil ChatGPT n'est pas branché : seules la recherche dans les documents indexés, les pièces jointes et la voix sont disponibles.",
    toolUnavailableClose: "Compris",
    dictate: "Dictée vocale",
    dictateStop: "Arrêter la dictée",
    dictateListening: "Dictée en cours. Parlez, le texte s'ajoute à votre question.",
    voiceMode: "Mode vocal",
    voiceModeClose: "Fermer le mode vocal",
    voiceListening: "Je vous écoute",
    voiceProcessing: "Recherche dans les documents indexés",
    voiceSpeaking: "Lecture de la réponse",
    voiceSend: "Envoyer",
    voiceRetry: "Réécouter",
    voiceUnsupportedTitle: "La voix n'est pas disponible",
    voiceUnsupportedBody:
      "Ce navigateur ne propose pas la reconnaissance vocale. Saisissez votre question, ou ouvrez Ubuntu IA dans Chrome ou Edge.",
    voiceDeniedTitle: "Micro non autorisé",
    voiceDeniedBody:
      "Autorisez le microphone dans les paramètres du navigateur, puis relancez la dictée ou le mode vocal.",
    voiceErrorTitle: "La dictée a été interrompue",
    voiceErrorBody: "Réessayez, ou saisissez votre question.",
    attachmentOnlyPrompt: "Analyse les pièces jointes au regard des documents internes indexés.",
    attachmentsLabel: "Pièces jointes",
    removeAttachment: "Retirer {name}",
    attachmentTooBig: "« {name} » dépasse 20 Mo. Réduisez-le avant de le joindre.",
    attachmentType:
      "« {name} » n'est pas accepté. Joignez un PDF, Word, Excel, PowerPoint, CSV, texte, image ou infographie.",
    attachmentLimit: "Vous pouvez joindre jusqu'à 8 fichiers à une question.",
    historyOpen: "Conversations",
    historyClose: "Fermer l'historique",
    menuOpen: "Ouvrir le menu",
    menuClose: "Fermer le menu",
    sourcesHeading: "Sources utilisées",
    extractLabel: "Extrait",
    emptyTitle: "Interrogez la base documentaire",
    emptyBody:
      "Posez une question en langage courant. Ubuntu IA répond uniquement à partir des documents et pages indexés par les administrateurs, et cite toujours ses sources.",
    emptyHint: "Exemple : Quelle est la procédure d'achat interne ?",
    historyLoading: "Chargement de vos conversations",
    historyErrorTitle: "L'historique n'a pas pu être chargé",
    historyErrorBody: "Vos conversations enregistrées sont inaccessibles pour le moment.",
    retryHistory: "Réessayer le chargement",
    noConversations: "Aucune conversation pour l'instant.",
    validationEmpty: "Saisissez une question pour interroger les documents indexés.",
    pendingAnnouncement: "Recherche dans les documents indexés.",
    noSourceTitle: "Aucun document ne permet de répondre",
    noSourceBody:
      "Ubuntu IA n'a trouvé aucun passage assez proche dans les documents indexés. Reformulez la question, ou demandez à un administrateur d'ajouter la source manquante.",
    noSourceAction: "Reformuler la question",
    errorTitle: "La réponse n'a pas pu être générée",
    errorBody:
      "Votre question est conservée. Vous pouvez relancer la recherche sans la ressaisir.",
    retryAnswer: "Relancer la recherche",
    timeoutTitle: "Le délai d'attente est dépassé",
    timeoutBody:
      "Ubuntu IA n'a pas confirmé si une réponse a été produite. Vérifiez l'historique avant de renvoyer la même question, pour éviter un doublon.",
    offlineTitle: "Connexion interrompue",
    offlineBody:
      "La recherche ne peut pas aboutir tant que le réseau est indisponible. Votre question reste affichée.",
    offlineBanner: "Vous êtes hors ligne. Les nouvelles questions ne peuvent pas être envoyées.",
  },
  admin: {
    tabs: {
      label: "Sections d'administration",
      documents: "Documents",
      access: "Accès",
      domains: "Domaines e-mail",
    },
    pageTitle: "Documents indexés",
    pageLead:
      "Ajoutez, suivez ou retirez les fichiers et pages qui alimentent Ubuntu IA. Une page web est indexée une par une.",
    uploadTitle: "Indexer un fichier",
    uploadLead:
      "PDF, Word, Excel (.xlsx, .xls), PowerPoint, CSV, images et infographies, jusqu'à 20 Mo. Le modèle lit le texte, les tableaux et le contenu visuel.",
    uploadDrop: "Déposez un fichier ici, ou",
    uploadBrowse: "choisir un fichier",
    urlTitle: "Indexer une page web",
    urlLabel: "Adresse de la page",
    urlPlaceholder: "https://soficau-ubuntu.com/page",
    urlHint: "Une seule page à la fois. L'indexation d'un site entier n'est pas disponible.",
    urlSubmit: "Indexer la page",
    urlSubmitting: "Récupération de la page",
    categoryLabel: "Catégorie",
    categoryIndexLabel: "Catégorie d'indexation",
    categoryIndexHint:
      "Les nouveaux fichiers et pages seront classés dans cette catégorie.",
    categoryFilterLabel: "Afficher",
    categoryFilterHint:
      "Ne voir que les fichiers et liens d'une catégorie, ou toute la base.",
    categoryFilterAll: "Toutes les catégories",
    categoriesTitle: "Catégories",
    categoryAddTitle: "Nouvelle catégorie",
    categoryAddLabel: "Nom de la catégorie",
    categoryAddPlaceholder: "Ex. Juridique",
    categoryAddHint: "Elle sera proposée à l'indexation et dans le filtre.",
    categoryAdd: "Ajouter la catégorie",
    categoryAdded: "La catégorie « {label} » est disponible.",
    emptyFilterTitle: "Aucun document dans « {label} »",
    emptyFilterBody:
      "Aucun fichier ni lien n'est classé dans cette catégorie pour le moment. Indexez une source ici, ou affichez toutes les catégories.",
    emptyFilterAction: "Voir toutes les catégories",
    tableLabel: "Documents de la base de connaissances",
    columns: {
      title: "Titre",
      category: "Catégorie",
      source: "Origine",
      status: "Indexation",
      date: "Ajouté le",
      actions: "Actions",
    },
    sourceFile: "Fichier",
    sourceUrl: "Page web",
    status: {
      en_attente: "En attente",
      en_cours: "Indexation en cours",
      termine: "Indexé",
      erreur: "Échec",
    },
    retryIndex: "Relancer l'indexation",
    delete: "Supprimer",
    loading: "Chargement des documents",
    loadErrorTitle: "La liste des documents n'a pas pu être chargée",
    loadErrorBody: "Les documents déjà indexés n'apparaissent pas. La base n'a pas été modifiée.",
    retryLoad: "Réessayer",
    emptyFirstTitle: "Aucun document n'est encore indexé",
    emptyFirstBody:
      "Ajoutez un PDF, Word, Excel, PowerPoint, CSV, image ou infographie, ou l'adresse d'une page web, pour constituer la base de connaissances.",
    emptyClearedTitle: "Tous les documents ont été retirés",
    emptyClearedBody:
      "La base de recherche est vide. Les réponses déjà affichées dans les conversations restent visibles, mais les nouvelles questions n'auront plus de source.",
    emptyAction: "Ajouter un fichier",
    queued: "« {title} » est en cours d'indexation.",
    indexed: "« {title} » est indexé et disponible pour la recherche.",
    indexFailed: "L'indexation de « {title} » a échoué. Le document n'est pas cherchable.",
    deleted: "« {title} » a été retiré de la base de recherche.",
    errors: {
      fileType:
        "Ce format n'est pas accepté. Envoyez un PDF, Word, Excel, PowerPoint, CSV, texte, image ou infographie.",
      fileSize: "Le fichier dépasse 20 Mo. Réduisez-le ou découpez-le avant de l'envoyer.",
      ingest: "L'indexation n'a pas pu démarrer. Réessayez dans un instant.",
      urlRequired: "Indiquez l'adresse complète de la page à indexer.",
      urlFormat:
        "Cette adresse n'est pas valide. Utilisez une URL complète, par exemple https://soficau-ubuntu.com/page.",
      category: {
        required: "Indiquez le nom de la catégorie.",
        invalid: "Ce nom n'est pas utilisable. Saisissez des lettres ou des chiffres.",
        duplicate: "Cette catégorie existe déjà.",
        unavailable: "La catégorie n'a pas pu être enregistrée. Réessayez.",
      },
    },
    confirm: {
      cancel: "Annuler",
    },
    indexFileTitle: "Indexer ce fichier ?",
    indexFileBody:
      "« {title} » sera classé dans {category}. L'indexation ne commence qu'après confirmation.",
    indexFileConfirm: "Indexer le fichier",
    indexUrlTitle: "Indexer cette page ?",
    indexUrlBody:
      "{url} sera classée dans {category}. L'indexation ne commence qu'après confirmation.",
    indexUrlConfirm: "Indexer la page",
    addCategoryConfirmTitle: "Ajouter cette catégorie ?",
    addCategoryConfirmBody:
      "« {label} » sera proposée à l'indexation et dans le filtre des documents.",
    addCategoryConfirm: "Ajouter la catégorie",
    categorySaving: "Enregistrement de la catégorie",
    retryTitle: "Relancer l'indexation ?",
    retryBody: "L'indexation de « {title} » va redémarrer. Le document n'est pas encore cherchable.",
    retryConfirm: "Relancer l'indexation",
    retryAll: "Relire les fichiers déjà indexés",
    retryAllTitle: "Relire tous les documents ?",
    retryAllBody:
      "Ubuntu IA va relire les fichiers et pages déjà enregistrés, y compris les images, tableurs et présentations, avec les extracteurs actuels.",
    retryAllConfirm: "Relire tous les documents",
    retryAllQueued: "{count} document(s) sont en cours de relecture.",
    deleteTitle: "Supprimer « {title} » ?",
    deleteBody:
      "Ce document et tous ses extraits seront retirés de la recherche. Les réponses déjà affichées dans les conversations ne changeront pas, mais Ubuntu IA ne s'appuiera plus sur cette source.",
    deleteConfirm: "Supprimer le document",
    deleteCancel: "Conserver le document",
    deleting: "Suppression en cours",
    forbiddenTitle: "Cette page est réservée aux administrateurs",
    forbiddenBody:
      "Vous êtes connecté en tant que collaborateur. L'ajout et la suppression de documents ne sont pas disponibles sur ce compte.",
    forbiddenAction: "Retourner à la conversation",
    domains: {
      pageTitle: "Domaines e-mail autorisés",
      pageLead:
        "Seules les adresses de ces domaines peuvent se connecter à Ubuntu IA. Retirer un domaine bloque immédiatement les prochaines connexions liées.",
      addTitle: "Autoriser un domaine",
      fieldLabel: "Domaine",
      fieldHint: "Sans @. Exemple : ubuntu-grp.com",
      fieldPlaceholder: "ubuntu-grp.com",
      add: "Ajouter le domaine",
      adding: "Ajout en cours",
      addConfirmTitle: "Autoriser ce domaine ?",
      addConfirmBody: "Les adresses @{domain} pourront ensuite se connecter à Ubuntu IA.",
      addConfirm: "Ajouter le domaine",
      loading: "Chargement des domaines autorisés",
      loadErrorTitle: "La liste des domaines n'a pas pu être chargée",
      loadErrorBody:
        "Les domaines déjà enregistrés n'apparaissent pas. La liste utilisée à la connexion n'a pas été modifiée.",
      retryLoad: "Réessayer",
      emptyTitle: "Aucun domaine n'est encore autorisé",
      emptyBody:
        "Ajoutez au moins un domaine professionnel, sinon personne ne pourra se connecter.",
      tableLabel: "Domaines autorisés à la connexion",
      columns: {
        domain: "Domaine",
        date: "Ajouté le",
        actions: "Actions",
      },
      delete: "Retirer",
      lastHint:
        "Au moins un domaine doit rester autorisé, sinon plus personne ne pourra se connecter.",
      added: "Les adresses @{domain} peuvent maintenant se connecter.",
      removed: "Les adresses @{domain} ne sont plus acceptées à la connexion.",
      deleteTitle: "Retirer @{domain} ?",
      deleteBody:
        "Les prochaines connexions avec une adresse @{domain} seront refusées. Les sessions déjà ouvertes restent actives jusqu'à la déconnexion.",
      deleteBodyOwn:
        "Votre propre adresse utilise @{domain}. Après ce retrait, vous ne pourrez plus vous reconnecter avec ce compte tant que le domaine n'est pas réautorisé.",
      deleteConfirm: "Retirer le domaine",
      deleteCancel: "Conserver le domaine",
      deleting: "Retrait en cours",
      errors: {
        required: "Indiquez le domaine à autoriser.",
        invalid:
          "Ce domaine n'est pas reconnu. Saisissez un nom d'hôte, par exemple ubuntu-grp.com.",
        duplicate: "Ce domaine est déjà autorisé.",
        last: "Il doit rester au moins un domaine autorisé.",
        unavailable:
          "Le domaine n'a pas pu être enregistré. Réessayez, la liste n'a pas changé.",
      },
    },
    access: {
      pageTitle: "Accès",
      pageLead:
        "Invitez une personne par e-mail, attribuez-lui un rôle, puis elle choisit son mot de passe avant d'entrer dans Ubuntu IA.",
      inviteTitle: "Inviter une personne",
      prenomLabel: "Prénom",
      nomLabel: "Nom",
      emailLabel: "Adresse e-mail",
      emailHint: "L'invitation part vers cette adresse. Le domaine doit être autorisé.",
      roleLabel: "Rôle",
      roleAdmin: "Administrateur",
      roleUser: "Collaborateur",
      send: "Envoyer l'invitation",
      sending: "Envoi de l'invitation",
      sent: "Invitation envoyée à {email}. La personne doit d'abord configurer son mot de passe.",
      inviteConfirmTitle: "Envoyer cette invitation ?",
      inviteConfirmBody:
        "{name} ({email}) recevra un lien pour choisir son mot de passe en tant que {role}.",
      inviteConfirm: "Envoyer l'invitation",
      resendConfirmTitle: "Renvoyer le lien ?",
      resendConfirmBody: "Un nouveau lien d'invitation sera envoyé à {email}.",
      resendConfirm: "Renvoyer le lien",
      loading: "Chargement des accès",
      loadErrorTitle: "Les accès n'ont pas pu être chargés",
      loadErrorBody: "La liste des comptes et des invitations n'apparaît pas. Rien n'a été modifié.",
      retryLoad: "Réessayer",
      peopleTitle: "Comptes",
      peopleEmptyTitle: "Aucun compte n'est encore listé",
      peopleEmptyBody: "Les personnes qui auront accepté une invitation apparaîtront ici.",
      peopleLabel: "Comptes Ubuntu IA",
      invitationsTitle: "Invitations",
      invitationsEmptyTitle: "Aucune invitation en cours",
      invitationsEmptyBody: "Envoyez une invitation pour qu'une personne configure son mot de passe.",
      invitationsLabel: "Invitations envoyées",
      resend: "Renvoyer le lien",
      resending: "Nouvel envoi",
      resent: "Un nouveau lien a été envoyé à {email}.",
      columns: {
        name: "Nom",
        email: "E-mail",
        role: "Rôle",
        status: "État",
        date: "Envoyée le",
        actions: "Actions",
      },
      status: {
        pending: "En attente",
        expired: "Expirée",
        accepted: "Compte créé",
      },
      errors: {
        prenom: "Indiquez le prénom.",
        nom: "Indiquez le nom.",
        email: "Indiquez une adresse e-mail professionnelle valide.",
        role: "Choisissez le rôle Administrateur ou Collaborateur.",
      },
    },
  },
  invite: {
    title: "Configurer votre mot de passe",
    lead: "Bonjour {name}. Choisissez un mot de passe pour ouvrir Ubuntu IA en tant que {role}.",
    passwordLabel: "Mot de passe",
    confirmLabel: "Confirmer le mot de passe",
    passwordHint: "Au moins 8 caractères. Les deux saisies doivent être identiques.",
    submit: "Enregistrer et entrer",
    submitting: "Création du compte",
    invalidTitle: "Ce lien d'invitation n'est pas valide",
    invalidBody: "Demandez à un administrateur de vous renvoyer une invitation.",
    expiredTitle: "Ce lien d'invitation a expiré",
    expiredBody: "Demandez à un administrateur de vous renvoyer un nouveau lien.",
    usedTitle: "Ce lien a déjà été utilisé",
    usedBody: "Connectez-vous avec l'adresse et le mot de passe déjà choisis.",
    usedAction: "Aller à la connexion",
    backAction: "Retour à la connexion",
    mismatch: "Les deux saisies doivent être identiques.",
    tooShort: "Le mot de passe doit contenir au moins 8 caractères.",
    loading: "Vérification de l'invitation",
  },
  categories: {
    rh: "RH",
    finance: "Finance",
    procedures: "Procédures",
    projets: "Projets",
    institutionnel: "Institutionnel",
  },
} as const;

export type Copy = typeof copy;
